name: ci

on:
  workflow_dispatch:
  push:
    paths:
      - docs/**
  pull_request:
    paths:
      - docs/**

jobs:
  retype-build:
    name: Retype build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.ACTIONS_TOKEN }}

      - uses: retypeapp/action-build@latest

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Rebuild
          file_pattern: docs/**
          commit_user_name: 858858+Bubka@users.noreply.github.com
          commit_user_email: Bubka
          commit_author: Bubka <858858+Bubka@users.noreply.github.com>
